openapi: 3.0.0
info:
    title: Graph API Plugin to access data from Entra ID, Intune and other Microsoft solutions
    description: Retrieve information from the Graph API.
    version: "1.0"
servers:
    - url: https://graph.microsoft.com/v1.0
paths:
    /identity/conditionalAccess/policies:
        get: 
            operationId: ListCAPolicies
            summary: List all Entra ID Conditional Access Policies. 
            responses:
                200:
                  description: Successful retrieval. 
                401:
                  description: Unsuccessful authentication.
