openapi: 3.0.0
info:
  title: Graph API Plugin to Access Custom Domains in Entra ID
  description: Use this skill to retrieve the list of custom domain names defined in your Entra ID tenant. For example, use this to view domains configured for organizational use.
  version: "1.0"
x-metadata:
  name: ListCustomDomains
  displayName: Retrieve list of custom domains in Entra ID
  samplePrompts:
    - "List all custom domain names in my Entra ID tenant."
    - "What custom domains are defined in my Entra ID?"
    - "Show the custom domain names configured in my Entra ID tenant."
servers:
  - url: https://graph.microsoft.com/v1.0
    description: Microsoft Graph API
paths:
  /domains:
    get:
      summary: Retrieve custom domains
      description: Retrieve the list of custom domains configured in the Entra ID tenant.
      responses:
        '200':
          description: A list of custom domains in the tenant.
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          description: The unique identifier of the domain.
                        authenticationType:
                          type: string
                          description: The authentication type of the domain (e.g., Managed or Federated).
                        isDefault:
                          type: boolean
                          description: Indicates whether this is the default domain.
                        isVerified:
                          type: boolean
                          description: Indicates whether the domain has been verified.
                        capabilities:
                          type: array
                          items:
                            type: string
                          description: A list of capabilities assigned to the domain (e.g., Email, SSO).
        '401':
          description: Unauthorized. Authentication failed or access token is missing.
        '403':
          description: Forbidden. The authenticated user does not have permission to access this resource.
      security:
        - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
